### PR TITLE
fix cergen for subjectAltName

### LINKED ISSUE #274: certificate subject-alternative-name doesn't work
playbooks/ops/certgen/* adds multiple SAN in certificate but not works as expecting.

```
openssl x509 -text --noout -in vars/keyfiles/peerOrganizations/org0.example.com/ca/ca1.org0.example.com-cert.pem
:
            X509v3 Subject Alternative Name: 
                IP Address:54.250.86.14, DNS:ca1.org0.example.com DNS.2:ca1-org0-example-com

# in ca1 container
fabric-ca-client enroll -u https://admin:adminpw@ca1-org0-example-com:7054 --tls.certfiles ${FABRIC_CA_SERVER_CA_CERTFILE}
:
Post https://ca1-org0-example-com:7054/enroll: x509: certificate is valid for ca1.org0.example.com DNS.2:ca1-org0-example-com, not ca1-org0-example-com
```

subjectAltName should be 'IP:...,IP:...,DNS:...,DNS:..." in multiple case (all keywords are IP or DNS but  not  IP.2 or DNS.2)

### PR DESCRIPTION
**Pull request by itaru2622**
fix #274

### CODE REVIEW

**Comment by litong01** [comment]
Why that needs to be fixed? SAN specification should contains the sequence number.

**Comment by itaru2622** [comment]
@litong01 as I described in issue #274. 

fabric-ca-client enroll -u https://ca1-org0-example-com:7054  was failed even ca1-org0-example-com is declared in san DNS.2. 
when I changed "DNS.2:" to "DNS:" in san, the same enroll request was succeeded.

I checked common HTTPS server certs,  and found all following sites are using "DNS:" style but not "DNS.2:" style.
- ietf.org
- iana.org
- google.com
- amazon.com
- github.com
- kubernetes.io

I don't think both of ietf.org and iana.org breaks specification.
in openssl sample document,  "DNS.2" style exists, but I couldn't find "DNS.2" style in recent specification.

If you mind, I keep "DNS.2" style and just add "DNS:" style, like: 
```
subjectAltName=IP.1:{{ endpoint_address }},DNS.1:{{partycn}},DNS.2:{{ partycn|replace('.','-') }},IP:{{ endpoint_address }},DNS:{{partycn}},DNS:{{ partycn|replace('.','-') }}
```

what, do you think?

**Comment by poweruserincary** [comment]
hmmm. I think that the request and the final cert are different thing. When you look at the cert itself, it indeed look like that, but when you create the request for cert, the syntax is a bit different. Can you check the produced the cert? I think the produced cert does not have the sequence number.

    On Monday, September 20, 2021, 2:02:04 PM EDT, itaru2622 ***@***.***> wrote:  
 
 


@litong01 as I described in issue #274.

fabric-ca-client enroll -u https://ca1-org0-example-com:7054 was failed even ca1-org0-example-com is declared in san DNS.2.
when I changed "DNS.2:" to "DNS:" in san, the same enroll request was succeeded.

I checked common HTTPS server certs, and found all following sites are using "DNS:" style but not "DNS.2:" style.
   
   - ietf.org
   - iana.org
   - google.com
   - amazon.com
   - github.com
   - kubernetes.io

I don't think both of ietf.org and iana.org breaks specification.
in openssl sample document, "DNS.2" style exists, but I couldn't find "DNS.2" style in recent specification.

If you mind, I keep "DNS.2" style and just add "DNS:" style, like:
subjectAltName=IP.1:{{ endpoint_address }},DNS.1:{{partycn}},DNS.2:{{ partycn|replace('.','-') }},IP:{{ endpoint_address }},DNS:{{partycn}},DNS:{{ partycn|replace('.','-') }}

what, do you think?


—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by itaru2622** [comment]
@poweruserincary  I investigated about certificates and openssl request.

- investigation of ietf.org certificate (saved via browser):
```
openssl x509 -text -noout -in ietf.cert
:
    X509v3 Subject Alternative Name: 
         DNS:*.ietf.org, DNS:ietf.org

asn.1 decoder (http://lapo.it/asn1js/ or similar sites) says :

SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.17 subjectAltName (X.509 extension)
          OCTET STRING (24 byte) 3016820A2A2E696574662E6F72678208696574662E6F7267
            SEQUENCE (2 elem)
              [2] (10 byte) *.ietf.org
              [2] (8 byte) ietf.org
```

- investigation of certificate generated by current main branch

  as you can see below:
     - openssl x509 parser does't print comma(',') before DNS.2: but print before "DNS:"
     - asn.1 decoder also cannot detect second DNS name.
     - I guesses that  'DNS.2" style is not detected as delimiter of SAN elements and
       both parser detect it like DNS: "ca1.org0.example.com DNS.2:ca1-org0-example-com".
       i.e. "DNS.2" style gives bad effect on other SAN element.
       fortunately, ca1.org0.example.com is specified in CN, so current main branch can work
       with IP address and FQDN(=CN)

```
openssl x509 -text
:
   X509v3 Subject Alternative Name: 
         IP Address:54.250.86.14, DNS:ca1.org0.example.com DNS.2:ca1-org0-example-com

ans.1 decoder says:

SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.17 subjectAltName (X.509 extension)
          OCTET STRING (57 byte) 3037870436FA560E822F6361312E6F7267302E6578616D706C652E636F6D20444E532E…
            SEQUENCE (2 elem)
              [7] (4 byte) 36FA560E
              [2] (47 byte) ca1.org0.example.com DNS.2:ca1-org0-example-com
```

- investigation of certificate generated by my PR branch

  as you can see below:
    - openssl x509 parser and asn.1 deccoder detect all SAN elements as expected.
    - this certificate has sequence in asn.1 format

```
openssl x509 -text -noout -in vars/keyfiles/peerOrganizations/org0.example.com/ca/ca1.org0.example.com-cert.pem
:
    X509v3 Subject Alternative Name: 
         IP Address:54.250.86.14, DNS:ca1.org0.example.com, DNS:ca1-org0-example-com, DNS:localhost, IP Address:127.0.0.1

asn.1 decoder says :

SEQUENCE (2 elem)
          OBJECT IDENTIFIER 2.5.29.17 subjectAltName (X.509 extension)
          OCTET STRING (69 byte) 3043870436FA560E82146361312E6F7267302E6578616D706C652E636F6D8214636131…
            SEQUENCE (5 elem)
              [7] (4 byte) 36FA560E
              [2] (20 byte) ca1.org0.example.com
              [2] (20 byte) ca1-org0-example-com
              [2] (9 byte) localhost
              [7] (4 byte) 7F000001
```

by above investigation, I think we should not specify SAN with 'DNS.2" style.
if we keep 'DNS.2" or "IP.2" style, other element may get  bad effect.

**Review by litong01 — APPROVED** [review]
Thanks for your investigation.

**Pull request merged**
