### PR TITLE
move some hard codings from templates to config_apply.yaml for easy changing behavior

### PR DESCRIPTION
**Pull request by itaru2622**
related to step1 in #243 ,

admin password and container run command for CA, orderer, peer, couchDB are defined in config_apply.yaml and template files refer them.

### CODE REVIEW

**Comment by litong01** [comment]
@itaru2622 many files changed, can you add a bit high level description on the design? Where will these values to defined? Thanks.

**Comment by itaru2622** [comment]
>  can you add a bit high level description on the design

@litong01 
two parameters, adminPassword and command, are newly involved in allXXX of config_apply.yaml for easy changing behavior.
'adminPassword' aims to change admin password, which was hard coded as 'adminpw'.
'command' aims to change container run command (corresponding to CMD in Dockerfile) for both docker and k8s cases.

These parameters were hard coded in many files, and it took efforts to change the value.
That is the reason  I need to change lots of files.

**Comment by litong01** [comment]
I am a bit concerned about changing the command against each node such as node start, this is flexible but I think it is probably not needed. Can we just deal with the password and leave the command alone? Thanks.

**Comment by itaru2622** [comment]
@litong01 I will revert command parameter for peer, orderer and couchdb, but not for fabric ca server. 
fabric ca server has lots of commannd options, and when user wants to add those option under his own risk, he has to edit multiple files at this moment. with this PR, he needs to edit just one file.

**Comment by litong01** [comment]
That sounds good. Thanks.

**Comment by itaru2622** [comment]
finished updating codes to follow the above conversation.
please review this PR.

**Review by litong01 — APPROVED** [review]

**Pull request merged**
