### PR TITLE
bumps couchdb to active version

### PR DESCRIPTION
**Pull request by itaru2622**
x hyperledger/fabric-couchdb:latest (last update: 8 month ago)
o couchdb:latest ( last update: days ago )

### CODE REVIEW

**Comment by litong01** [comment]
@itaru2622 I think there was a reason why the community couchdb cannot be used. Is that limitation gone now?

**Comment by itaru2622** [comment]
Yes I think so, even though I don't know exact reason.

my fabric works with comunity (apache ) couchdb in months.

**Comment by litong01** [comment]
Actually I do not think we should use the latest image which always change. Can simply break us. Can you use the newest version tag instead ?

**Comment by itaru2622** [comment]
@litong01 I changed tag.  x couchdb:latest  o couchdb:3

**Review by litong01 — APPROVED** [review]
Thanks

**Pull request merged**
