### PR TITLE
try to impl verbose option

### PR DESCRIPTION
**Pull request by SamYuan1990**
Hi MiniFab maintainers,

I noticed that there VERBOSE env but no impl for a VERBOSE feature of minifab commmand.
With this pr, I am try to impl VERBOSE option with `-vvvv` as "trace" level of ansible play book.

Thanks

Signed-off-by: SamYuan1990 <yy19902439@126.com>

### CODE REVIEW

**Review by litong01 — CHANGES_REQUESTED** [review]
If you look at the spec.yaml you will see the default one indicating the logging level to be debug. That is how fabric set logging level. To see more info during minifabric run, use -f default. Do not think this PR is needed.

**Comment by SamYuan1990** [comment]
> If you look at the spec.yaml you will see the default one indicating the logging level to be debug. That is how fabric set logging level. To see more info during minifabric run, use -f default. Do not think this PR is needed.

this pr is for minifab, not for fabric. `-f` 
```
  echo "    -f|--run-output           - minifabric run time output callback, can be 'minifab'(default), 'default', 'dense'"
```
just redirect output but do nothing with ansible log level.

**Review by litong01 — CHANGES_REQUESTED** [review]
I assume this flag will have to work with -f flag, right?

**Comment by SamYuan1990** [comment]
> I assume this flag will have to work with -f flag, right?

maybe not.

1. redirect log output to some where else.
1. changing log level.

are independent.

at my point of view...
1. in minifab ci seems we just tested with basic feature, but not specific/full coverage of commands and options which better to improve. I hope devops developer able to learn from CI jobs as `how to use minifab options, -f -l ...etc`?
1. in fact before this pr, VERBOSE env was set but not used and not clean up.
1. another point with confusing me, we have spec.yaml as mout of minifab lib, why not apply for other files?
1. `-c/-d ...` too many short cuts... maybe

**Comment by litong01** [comment]
@SamYuan1990 minifab uses its own output plugin which is also called minifab. Which was a special ansible plugin to do output with very little clutter. Not really sure how this flag will be processing the output. Can you post some output here with your flag on and off so that I can see what this flag does?

**Comment by SamYuan1990** [comment]
> @SamYuan1990 minifab uses its own output plugin which is also called minifab. Which was a special ansible plugin to do output with very little clutter. Not really sure how this flag will be processing the output. Can you post some output here with your flag on and off so that I can see what this flag does?

for sample:
https://github.com/hyperledger-labs/minifabric/pull/167/checks?check_run_id=1969850452#step:4:43

**Comment by litong01** [comment]
@SamYuan1990 there are quite a lot of exceptions from the output, see this

```
# Create certs using openssl **********************************
  All items completed
Callback Exception: 
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_queue_manager.py", line 389, in send_callback
    method(*new_args, **kwargs)
   File "/usr/lib/python3.8/site-packages/ansible/plugins/callback/minifab.py", line 251, in v2_runner_on_ok
    self._print_task_result(result, error=False, **kwargs)
   File "/usr/lib/python3.8/site-packages/ansible/plugins/callback/minifab.py", line 200, in _print_task_result
    self._print_host_or_item(r['item'],
Read vars_file './spec.yaml'
Read vars_file './playbooks/ops/opnames.yaml'```

are these expected?

**Comment by litong01** [comment]
It seems to me that this flag actually breaks minifab callback plugin.

**Comment by SamYuan1990** [comment]
> It seems to me that this flag actually breaks minifab callback plugin. That is the issue I was talking about earlier regarding if this has to be used with Ansible callback plugins such as default, dense etc.

ref here
https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-v

`-vvvv` is verbose mode to running ansible-playbook. so you mean the verbose, breaks running?

**Comment by litong01** [comment]
@SamYuan1990 see the exception I captured from the CI/Build which you referenced, each of the build actually shows the exception from the default callback. see this one, which is just one of the many exception. https://github.com/hyperledger-labs/minifabric/pull/167/checks?check_run_id=1969850524#step:4:130. As I said before, Minifabric uses its own callback plugin which is also called minifab. The code is in the plugin/callback directory as python code. It was specially made to remove the default ansible output clutter since users do not want to see enormous output coming out Minifabric. I can only think this verbose is really for the developers who develops minifabric which seems to me will have to be used with -f flag to indicate a default ansible callback plugin. If you really want to have this in, please also do some work with the default callback plugin to make sure it wont cause exceptions.

**Comment by SamYuan1990** [comment]
> @SamYuan1990 see the exception I captured from the CI/Build which you referenced, each of the build actually shows the exception from the default callback. see this one, which is just one of the many exception. https://github.com/hyperledger-labs/minifabric/pull/167/checks?check_run_id=1969850524#step:4:130. As I said before, Minifabric uses its own callback plugin which is also called minifab. The code is in the plugin/callback directory as python code. It was specially made to remove the default ansible output clutter since users do not want to see enormous output coming out Minifabric. I can only think this verbose is really for the developers who develops minifabric which seems to me will have to be used with -f flag to indicate a default ansible callback plugin. If you really want to have this in, please also do some work with the default callback plugin to make sure it wont cause exceptions.

I see

**Comment by litong01** [comment]
@SamYuan1990 will you continue to pursue this PR? If not, please close this one. Thanks.

**Comment by SamYuan1990** [comment]
close for now. and will reopen when completed.

**Pull request closed without merging**
