### PR TITLE
Change latest Fabric version from 2.2.0 to 2.3.0

### PR DESCRIPTION
**Pull request by mvkillu**
Changed the current Fabric release version number in the docs from 2.2.0 to 2.3.0

### CODE REVIEW

**Review by litong01 — APPROVED** [review]
Thanks

**Comment by litong01** [comment]
Looks like that you have not signed the contribution agreement. Please work with @ryjones to get it resolved. Maybe just missing sign off.

**Comment by mvkillu** [comment]
@ryjones - could you help me with this?

This is what I tried. I cloned the minifabric repo and I followed the instructions mentioned on https://github.com/hyperledger-labs/minifabric/pull/259/checks?check_run_id=3386511950

image

**Comment by ryjones** [comment]
> @ryjones - could you help me with this?
> 
> This is what I tried. I cloned the minifabric repo and I followed the instructions mentioned on https://github.com/hyperledger-labs/minifabric/pull/259/checks?check_run_id=3386511950
> 
> image

You need to clone using the git protocol not https.

**Comment by mvkillu** [comment]
@litong01 - I signed off the commit and it seems the DCO is not an issue anymore. But the build operation is timed out and is failing. Could you pls take a look at it. Thank you.

**Pull request merged**
