### PR TITLE
feature: configurable extra option for docker run command

### LINKED ISSUE #155: feature suggestion:  configurable extra option for docker run command
current latest minifabric can set additional environment variable to docker containers via settings section in spec.yaml
but it doesn't have a way to set additional option to docker run command.
then, I cannot specify '--restart" nor "--log-opt" policies  even I want to use minifabric  in long run use cases.

first I think adding  '--restart=always'  by hard coding style into playbook, but logging policy may be different in each case.
then, I think it is good to have configurable extra docker option in spec.yaml as described bellow snippet.
it may be single(choice 1, same option to all containers), or multiple (choice 2, different option for each type).

I'm not sure which choice is preferable for minifabric maintainers. any suggestion?

```yaml
# ansible playbooks
- name: Start xxx 
  command: >-
    docker run -d ... --name {{item.fullname}} ... {{ extra_docker_option }} ... # append extra docker option.
```

```yaml
# spec.yaml
# choice 1: single;  add the same option to all containers(ca,peer,orderer)
fabric:
  ca:
  peers:
  orderers:
  settings:
  extra_docker_option: " --restart=always  --log-opt max_size=Xmb --log-opt max_file=N " # new key

# choice 2: different option in each type, same style as 'settings( for environment variable)'.
fabric:
  : 
  settings:
  extra_docker_option: 
     ca:       " --restart=always  --log-opt max_size=3mb  --log-opt max_file=3"
     peers:    " --restart=always  --log-opt max_size=10mb --log-opt max_file=10"
     orderers: " --restart=always  --log-opt max_size=5mb  --log-opt max_file=5"
```

### PR DESCRIPTION
**Pull request by itaru2622**
This PR takes  choice1 (single parameter), as discussed in issue #155.
close #155 .

### CODE REVIEW

**Comment by litong01** [comment]
Please use one commit.

**Comment by litong01** [comment]
It is very hard to review all your changes with multiple commits.

**Comment by itaru2622** [comment]
@litong01  I rebased PR and now it has just single commit.

**Review by litong01 — APPROVED** [review]
Thanks for your contribution

**Pull request merged**
