### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by davidkhala**
stale-bot powered by Github Workflow

### CODE REVIEW

**Comment by ryjones** [comment]
What is the advantage of using this, instead of probot?

**Review by ryjones — COMMENTED** [review]
Why use this instead of probot?

**Comment by davidkhala** [comment]
@ryjones 
Good suggestion! I just get to know probot-stale. 

I am not member of Hyperledger-labs thus I have no access right to install any probot Github App.

**Comment by ryjones** [comment]
Stale is already installed on this org - if you create .github/stale.yml with the settings you used, it should work

**Review by ryjones — APPROVED** [review]

**Pull request merged**
