### PR TITLE
fix certificates mapping and support fabric 1.4.x series on k8s.

### LINKED ISSUE #246: Unable to get the minifab.cmd file
Hi there,

I'm very new to Hyperledger Fabric and not sure what steps I've missed. 

I've run the below command on my Windows 10 and tried to start minifab with no success.

mkdir %userprofile%\mywork & cd %userprofile%\mywork & curl -o minifab.cmd -sL https://tinyurl.com/y3gupzby

Then, I tried to recheck minifab.cmd by going to https://tinyurl.com/y3gupzby and it said 404: Not Found.

It seems the file is missing? Can you please help fix this issue?

Thanks a lot for your help.

### PR DESCRIPTION
**Pull request by itaru2622**
close #246

test OK     fabric 1.4.8 (NEW!)
test OK     fabric 2.3.2 (as regression test)
test NG     fabric 1.4.7 or older.  reason: dependency docker image fabric-ccenv:latest is gone from dockerhub

Signed-off-by: itaru2622 <itaru2622@gmail.com>

### CODE REVIEW

**Review by litong01 — COMMENTED** [review]
The reason that I did not upload bulk file to k8s was for performance concerns. Seems to me this pr is doing that. The performance of unpacking tar file onto k8s storage vary big time cross different cloud. I wonder if you have a rather large fabric cloud such as 8 orgs each with like 4 to 5 peer to see how things go.

**Comment by itaru2622** [comment]
I understood your stance.  so I will withdraw this PR after attaching the patch file into the issue #264 page.
I don't have time to re-produce uploading certs with correct path in another way to support older fabric version.

**Comment by litong01** [comment]
@itaru2622 minifabric does not support 1.4.3 or lower. I think that 1.4.4 or later are ok. are you saying this wont work for any version of 1.4.x on k8s?

**Comment by itaru2622** [comment]
@litong01  No. any fabric 1.4 series doesn't work on k8s because of cert private key path trouble, as described in #264. any orderer nor peer cannot run and keep crashing as bellow.

```bash
kubectl get pod ...
:
mysite          orderer1-example-com-0                      0/1     CrashLoopBackOff   7          14m
mysite          orderer2-example-com-0                      0/1     CrashLoopBackOff   7          14m
mysite          orderer3-example-com-0                      0/1     CrashLoopBackOff   7          14m
mysite          peer1-org0-example-com-0                    1/2     CrashLoopBackOff   7          14m
mysite          peer1-org1-example-com-0                    1/2     CrashLoopBackOff   7          14m

kubectl logs -f -n mysite          peer1-org0-example-com-0 -c peer

2021-08-31 06:00:32.880 UTC [viperutil] getKeysRecursively -> DEBU 001 Found map[string]interface{} value for peer.BCCSP
:
2021-08-31 06:00:32.888 UTC [main] InitCmd -> ERRO 031 Cannot run peer because error when setting up MSP of type bccsp from directory /etc/hyperledger/fabric/msp: KeyMaterial not found in SigningIdentityInfo
```

**Pull request closed without merging**
